# Generated by Django 4.1.3 on 2023-01-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rubric_rubricmanager_subrubric_superrubric_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RubricManager',
        ),
    ]
